### PR TITLE
Complete navbar feature

### LINKED ISSUE #2: 2. As a user, I want to be able to navigate to all the pages in the application by clicking the links in the nav bar
## Summary

Users need to be able to navigate between the pages of our application in order to access all of its features. There is a navigation bar in the `Layout.jsx` component, but it's not quite feature-complete: the links in the nav element don't actually allow the user to navigate from page to page.

## Acceptance criteria
- [x] The `nav` element is added to the `Layout` component
- [x] Links to the "Home", "List", and "Add item" pages of the app are In the `nav` element
- [x] The links all function as expected using  the `NavLink` component from `react-router-dom`

## Notes
- The [official docs for the `NavLink` component](https://reactrouterdotcom.fly.dev/docs/en/v6/components/nav-link) will come in very handy!
- While a standard anchor element (`<a>`) _could_ allow a user to navigate from page to page, the `NavLink` component adds additional behavior that is essential to our app functioning correctly!

### PR DESCRIPTION
**Pull request by rdpfeifle**
## Description

Replaced the anchor tags with NavLink from react-router-dom

## Related Issue

closes #2 

## Acceptance Criteria

- [x] The links all function as expected using the NavLink component from react-router-dom

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

### Before

screenshot-before

### After

screenshot-after

## Testing Steps / QA Criteria

Click on each of the nav links to see if the URL jumps to the right page

### CODE REVIEW

**Comment by CorinaMurg** [comment]
This looks great, nice job!

**Comment by AslanTaheri** [comment]
Nice job! Everything looks good :)

**Review by CorinaMurg — APPROVED** [review]

**Review by AslanTaheri — APPROVED** [review]

**Review by cafloyd — APPROVED** [review]
Looks perfect!! Congrats on your first PR @rdpfeifle @shangguanwang !!

**Comment by mentalcaries** [comment]
Looks great! I'm glad that you also included screenshots for the PR!

**Pull request merged**
